services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: bghelperdb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  spring-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-backend
    restart: unless-stopped
    ports:
      - "8089:8089"
    volumes:
      - character-images:/data/images
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/bghelperdb
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongodb
    networks:
      - app-network

  next-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8089/api
    container_name: next-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8089/api
    depends_on:
      - spring-backend
    networks:
      - app-network

volumes:
  mongo-data:
  character-images:

networks:
  app-network:
    driver: bridge
